<?php

/**
 * @file
 * washuas.module
 * Drupal hooks and other helper functions for those hooks can go here
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_allowed_values_function().
 */
function washuas_rule_year_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  // Available drop year values.
  $thisyear = date('Y');
  $i = $thisyear;
  $options = [];
  while ($i >= 2000) {
    $options[$i] = $i;
    $i--;
  }
  return $options;
}

/**
 * Implements hook_views_query_alter().
 */
function washuas_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\Sql $query) {
    // Target the specific View and display.
    $account = \Drupal::currentUser();
    // Only show private nodes if user has a specific permission.
    if (!$account->hasPermission('access private content')) {
        // Add a condition to only show non-private content.
        $query->addWhereExpression(0, 'node_field_data.private is null');
    }
}
