# Plugin \Drupal\ckeditor5\Plugin\CKEditor5Plugin\ListPlugin
ckeditor5.plugin.ckeditor5_list:
  type: mapping
  label: List
  mapping:
    reversed:
      type: boolean
      label: 'Allow reverse list'
      constraints:
        NotNull: []
    startIndex:
      type: boolean
      label: 'Allow start index'
      constraints:
        NotNull: []
    styles:
      type: boolean
      label: 'Allow use of style type'
      constraints:
        NotNull: [ ]
