<?php
/**
 * @file
 * washuas_secure_content.module
 * Drupal hooks and other helper functions for those hooks can go here
 */

use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_install().
 */
function washuas_secure_content_install() {
  /** @var \Drupal\washuas\Services\EntityTools $entity_tools */
  $entity_tools = \Drupal::service('washuas.entitytools');

  // Create visibility taxonomy terms on install
  $entity_tools->createTerm('visibility', 'Public');
  $entity_tools->createTerm('visibility', 'Private');

}
/**
 * Implements hook_uninstall().
 */
function washuas_secure_content_uninstall(){
  /** @var \Drupal\washuas\Services\EntityTools $entity_tools */
  $entity_tools = \Drupal::service('washuas.entitytools');

  // Remove the Visibility Vocabulary
  \Drupal::configFactory()->getEditable('taxonomy.vocabulary.visibility')->delete();

  // Delete visibility taxonomy terms on install
  $entity_tools->deleteTerm('visibility', 'Public');
  $entity_tools->deleteTerm('visibility', 'Private');

  // Remove the Visibility taxo ref field from the nodes
  $field = FieldStorageConfig::loadByName('node', 'field_washuas_secure_content_vis');
  if ($field) {
    // Delete this field.
    $field->delete();
  }
}


/**
* Implements hook_form_alter().
 */
function washuas_secure_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {

  // Select the desired entity add/edit form.
  if (is_array($form['#theme']) && in_array('node_form', $form['#theme'])) {
    $config = \Drupal::configFactory()->getEditable('washuas_secure_content.settings');
    $config_values = $config->getRawData();

    $bundle = '';
    $form_object = $form_state->getFormObject();
    if ($form_object) {
      $bundle = $form_object->getEntity()->bundle();
    }

    // Only run on nodes that have been configured to use the visibility field
    foreach ($config_values as $config_key => $config_value) {
      if(($config->get($bundle.'_visibility_functionality')== 1)
        && (strpos($config_key, $bundle) !== FALSE) ) {
        // Ex 4. Create a custom collapsible container in the sidebar.
        $form['group_washus_secure_content_vis'] = [
          '#type' => 'details',
          '#group' => 'advanced', // This line places the container in the sidebar
          '#weight' => 5,  // ensure it displays after the permissions by term fieldset.
          '#title' => t('Visibility'),
          '#tree' => TRUE,
          '#access' => TRUE,
          '#open' => 'open'
        ];

        // Ex 4.1 Move a field into the custom container in the sidebar.
        if (!empty($form['field_washuas_secure_content_vis'])) {
          $form['field_washuas_secure_content_vis']['#weight'] = -1; // reset weight
          $form['field_washuas_secure_content_vis']['#group'] = 'group_washus_secure_content_vis';
        }

      }

    }
  }
}
